#!/usr/bin/env python3
"""Turn the Omarchy screensaver logo (logo.txt, drawn with half-block
characters) into the layout main.asm draws it with, in ../logo.inc.

Each character cell is one pixel wide and two pixels tall (its upper and lower
halves), so the logo keeps the square-pixel look it has in the terminal. The
effects give every cell a color index, and main.asm renders those 8 cells (one
tile's width) of a cell row at a time: a group, which makes 4 bytes of tile
data (both bit planes of its upper and lower pixel rows).

The logo's tiles sit in VRAM one tile row per 256 bytes, from $8100. Groups
whose cells are all blank are left out; their bytes stay zero. The rest are
rendered one after another into a framebuffer in VRAM order, so that it can
be copied in runs of consecutive bytes. The VBlank handler copies it in two
halves, one per frame, as the whole of it takes longer than a DMG's VBlank.

logo.inc has the groups' masks (which of their pixels are the logo's) and the
code that copies each half.

Usage: tools/logo.py [logo.txt]
"""

import sys
from pathlib import Path

W, H = 160, 144
ROOT = Path(__file__).resolve().parent.parent

# Which halves of a cell each character fills: (upper, lower)
HALVES = {" ": (0, 0), "▀": (1, 0), "▄": (0, 1), "█": (1, 1)}

# The most bytes a half can have for its copy to fit in a DMG's VBlank
MAX_HALF_BYTES = 200


def read_cells(path=None):
    """The logo as rows of (upper, lower) cells, padded to a multiple of 8 wide."""
    text = (Path(path) if path else ROOT / "logo.txt").read_text()
    rows = []
    for line in text.rstrip("\n").split("\n"):
        row = []
        for ch in line:
            if ch not in HALVES:
                sys.exit(f"logo.py: unsupported character {ch!r}")
            row.append(HALVES[ch])
        rows.append(row)
    width = max(len(r) for r in rows)
    padded = -(-width // 8) * 8
    return width, [r + [(0, 0)] * (padded - len(r)) for r in rows]


class Layout:
    """The logo's tiles, and its non-blank groups in VRAM order."""

    def __init__(self, width, cells):
        self.cells = cells
        self.cols, self.rows = len(cells[0]), len(cells)
        self.width, self.height = width, self.rows * 2
        if self.width > W or self.height > H:
            sys.exit(f"logo.py: logo is {self.width}x{self.height}, larger than the {W}x{H} screen")
        self.tw = self.cols // 8  # tiles per tile row
        self.th = -(-self.rows // 4)
        if self.tw > 16 or self.th > 8:
            sys.exit("logo.py: main.asm needs a logo at most 128 pixels wide and 64 tall")

        # (cell row, group column) for each non-blank group, in VRAM order
        self.groups = sorted(
            ((r, g) for r in range(self.rows) for g in range(self.tw) if any(map(any, self.group_cells(r, g)))),
            key=lambda rg: self.vram(*rg),
        )

    def group_cells(self, r, g):
        return self.cells[r][g * 8 : g * 8 + 8]

    def vram(self, r, g):
        """Where group (r, g)'s 4 bytes go in VRAM."""
        return 0x8100 + (r // 4) * 0x100 + g * 16 + (r % 4) * 4

    def mask(self, r, g, half):
        bits = 0
        for cell in self.group_cells(r, g):
            bits = bits << 1 | cell[half]
        return bits

    def halves(self):
        """The groups' VRAM addresses, split into two halves of about equal size."""
        addresses = [self.vram(r, g) for r, g in self.groups]
        split = (len(addresses) + 1) // 2
        a, b = addresses[:split], addresses[split:]
        if max(len(a), len(b)) * 4 > MAX_HALF_BYTES:
            sys.exit(f"logo.py: {len(addresses) * 4} bytes of tile data are too many to copy in two VBlanks")
        return a, b


def runs(addresses):
    """Group addresses merged into runs of consecutive bytes, as (start, length)."""
    out = []
    for address in addresses:
        if out and out[-1][0] + out[-1][1] == address:
            out[-1][1] += 4
        else:
            out.append([address, 4])
    return out


def main():
    layout = Layout(*read_cells(sys.argv[1] if len(sys.argv) > 1 else None))
    half_a, half_b = layout.halves()

    hexes = lambda bs: ", ".join(f"${b:02X}" for b in bs)
    lines = [
        "; Generated by tools/logo.py from logo.txt - do not edit.",
        "",
        f"DEF LOGO_W EQU {layout.width} ; in pixels",
        f"DEF LOGO_H EQU {layout.height}",
        f"DEF LOGO_TW EQU {layout.tw} ; in tiles",
        f"DEF LOGO_TH EQU {layout.th}",
        f"DEF LOGO_GROUPS EQU {len(layout.groups)}",
        f"DEF LOGO_HALF_A EQU {len(half_a) * 4} ; framebuffer bytes in the first half",
        f"DEF LOGO_FRAME_SIZE EQU {len(layout.groups) * 4}",
        "",
    ]
    for name, half in (("A", half_a), ("B", half_b)):
        lines += [f"; Copy framebuffer half {name}, from sp, to VRAM", f"MACRO COPY_HALF_{name}"]
        for start, length in runs(half):
            lines += [f"    ld hl, ${start:04X}", f"    POPSLIDE {length}"]
        lines += ["ENDM", ""]
    lines += [
        'SECTION "Logo", ROM0',
        "",
        "; Which pixels of each group's upper and lower pixel rows are the logo's",
        "LogoMasks::",
    ]
    for r, g in layout.groups:
        masks = [layout.mask(r, g, 0), layout.mask(r, g, 1)]
        lines.append(f"    db {hexes(masks)} ; row {r}, columns {g * 8}-{g * 8 + 7}")
    lines.append("")

    out = ROOT / "logo.inc"
    out.write_text("\n".join(lines))
    print(f"Wrote {out.relative_to(ROOT)}: {len(layout.groups)} groups, halves of {len(half_a) * 4} and {len(half_b) * 4} bytes")


if __name__ == "__main__":
    main()
