#!/usr/bin/env python3
"""Turn the Omarchy screensaver logo (logo.txt, drawn with half-block
characters) into Game Boy graphics in ../logo.inc: deduplicated 2bpp tiles and
a 20x18 tile map covering the whole 160x144 screen.

Each character cell is one pixel wide and two pixels tall (its upper and lower
halves), so the logo keeps the square-pixel look it has in the terminal. Logo
pixels use color 1, the background color 0; main.asm's palettes turn those
into white on black.

Usage: tools/logo.py [logo.txt]
"""

import sys
from pathlib import Path

W, H = 160, 144
ROOT = Path(__file__).resolve().parent.parent

# Which halves of a cell each character fills: (upper, lower)
HALVES = {" ": (0, 0), "▀": (1, 0), "▄": (0, 1), "█": (1, 1)}


def logo_pixels(text):
    rows = []
    for line in text.rstrip("\n").split("\n"):
        upper, lower = [], []
        for ch in line:
            if ch not in HALVES:
                sys.exit(f"logo.py: unsupported character {ch!r}")
            u, l = HALVES[ch]
            upper.append(u)
            lower.append(l)
        rows += [upper, lower]
    width = max(len(r) for r in rows)
    return [r + [0] * (width - len(r)) for r in rows]


def screen_pixels(logo):
    lw, lh = len(logo[0]), len(logo)
    if lw > W or lh > H:
        sys.exit(f"logo.py: logo is {lw}x{lh}, larger than the {W}x{H} screen")
    x0, y0 = (W - lw) // 2, (H - lh) // 2
    px = [[0] * W for _ in range(H)]
    for y, row in enumerate(logo):
        for x, c in enumerate(row):
            px[y0 + y][x0 + x] = c
    return px


def tile_bytes(px, tx, ty):
    """The 16 bytes of an 8x8 tile: per row, the low bit plane then the high."""
    out = []
    for y in range(ty * 8, ty * 8 + 8):
        lo = hi = 0
        for x in range(tx * 8, tx * 8 + 8):
            c = px[y][x]
            lo = lo << 1 | (c & 1)
            hi = hi << 1 | (c >> 1)
        out += [lo, hi]
    return tuple(out)


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "logo.txt"
    px = screen_pixels(logo_pixels(src.read_text()))

    tiles = [tuple([0] * 16)]  # tile 0 is blank, filling the rest of the screen
    index = {tiles[0]: 0}
    tilemap = []
    for ty in range(H // 8):
        row = []
        for tx in range(W // 8):
            t = tile_bytes(px, tx, ty)
            if t not in index:
                index[t] = len(tiles)
                tiles.append(t)
            row.append(index[t])
        tilemap.append(row)
    if len(tiles) > 256:
        sys.exit(f"logo.py: {len(tiles)} unique tiles, more than 256")

    hexes = lambda bs: ", ".join(f"${b:02X}" for b in bs)
    lines = [
        f"; Generated by tools/logo.py from {src.name} - do not edit.",
        "",
        'SECTION "Logo", ROM0',
        "",
        f"; {len(tiles)} unique 8x8 tiles, 2bpp",
        "LogoTiles::",
    ]
    lines += [f"    db {hexes(t)}" for t in tiles]
    lines += [
        "LogoTilesEnd::",
        "",
        "; 20x18 tile map, one row of tile indices per screen row",
        "LogoMap::",
    ]
    lines += [f"    db {hexes(r)}" for r in tilemap]
    lines += ["LogoMapEnd::", ""]

    out = ROOT / "logo.inc"
    out.write_text("\n".join(lines))
    print(f"Wrote {out.relative_to(ROOT)}: {len(tiles)} tiles")


if __name__ == "__main__":
    main()
